import type { Scenario } from "../types";

export const trustedVolumesRfq: Scenario = {
  slug: "trusted-volumes-rfq",
  exhibit: "EXH-037",
  title: "The Resolver That Trusted Too Much",
  tagline:
    "May 7, 2026. TrustedVolumes loses roughly $6.7M after a custom RFQ swap proxy lets an attacker register as trusted, replay stale orders, and choose someone else's transfer source.",
  category: "incident-response",
  difficulty: "intermediate",
  era: "2020s",
  year: "2026",
  estMinutes: 10,
  fictional: true,
  cwd: "/srv/rfq-desk",
  user: "responder",
  host: "eth-watch-07",
  role: "On-call incident responder for a DeFi market maker that settles RFQ orders through a custom Ethereum resolver.",
  objective:
    "Reconstruct why the resolver drained funds, separate the affected custom proxy from the wider aggregator, and write the first containment note.",
  briefing:
    "TrustedVolumes, a liquidity provider and resolver used by multiple DeFi protocols, confirmed a May 7 2026 exploit that drained about $6.7M. Public reporting tied the attack to a custom RFQ swap proxy, not 1inch's core aggregation contracts. Your evidence room contains a simplified config, resolver event log, transaction trace, and containment checklist. Work out which trust checks failed.",
  env: {
    USER: "responder",
    SHELL: "/bin/sh",
    PWD: "/srv/rfq-desk",
    CHAIN: "ethereum-mainnet",
  },
  ps: [
    "  PID TTY          TIME CMD",
    "  101 ?        00:00:01 systemd",
    "  288 ?        00:00:12 node watcher.js --chain mainnet",
    "  417 ?        00:00:03 geth attach --readonly",
    "  612 pts/0    00:00:00 sh",
    "  621 pts/0    00:00:00 ps",
  ],
  history: ["pwd", "ls", "cat ADVISORY.md"],
  files: {
    "/srv/rfq-desk/ADVISORY.md": {
      content: [
        "TrustedVolumes RFQ resolver exploit, May 7 2026",
        "",
        "Reported loss: about $6.7M total.",
        "Initial on-chain estimate: about $5.87M from the Ethereum resolver.",
        "Assets observed: 1,291 WETH, 206,282 USDT, 16.93 WBTC,",
        "                 and 1.26M USDC, later consolidated to ETH.",
        "",
        "Affected surface:",
        "  - TrustedVolumes-controlled custom RFQ swap proxy and resolver.",
        "  - Not the standard 1inch aggregation route or 1inch user funds.",
        "",
        "Public root-cause summary:",
        "  1) signer registration accepted an arbitrary caller",
        "  2) replay protection used a nonce that was not consumed",
        "  3) transfer source could be supplied by calldata",
        "",
        "Questions for first response:",
        "  - which contract was drained?",
        "  - how did the attacker become trusted?",
        "  - why did stale authorization still work?",
        "  - whose funds did the transferFrom source point at?",
      ].join("\n"),
    },
    "/srv/rfq-desk/contracts/resolver.config": {
      content: [
        "# production excerpt, simplified for incident response",
        "chain=ethereum-mainnet",
        "resolver=0x9bA0CF1588E1DFA905eC948F7FE5104dD40EDa31",
        "rfq_proxy=0xeEeEEe53033F7227d488ae83a",
        "owner_multisig=0xF00d00000000000000000000000000000000bEEF",
        "",
        "[signers]",
        "# Intended: only owner multisig can add market maker signers.",
        "# Deployed: registerSigner(address signer) was public.",
        "trusted_signer_01=0xBEEF00000000000000000000000000000000F00D",
        "",
        "[order_checks]",
        "domain_separator=rfq-proxy-v2-mainnet",
        "nonce_consumed=false",
        "expiry_required=true",
        "payer_source=calldata.from",
        "",
        "[integration_notes]",
        "1inch_standard_routes=not_affected",
        "user_facing_swap_ui=not_affected",
      ].join("\n"),
    },
    "/srv/rfq-desk/logs/events.log": {
      content: [
        "2026-05-07T06:11:02Z watcher boot chain=ethereum-mainnet block=25039211",
        "2026-05-07T06:16:44Z event RegisterSigner caller=0xC3EBDdEa4f69df717a8f5c89e7cF20C1c0389100 signer=0xC3EBDdEa4f69df717a8f5c89e7cF20C1c0389100 status=accepted",
        "2026-05-07T06:17:03Z event RFQFill order=0x71b3 signer=0xC3EBDdEa4f69df717a8f5c89e7cF20C1c0389100 nonce=8842 nonceState=unused from=TrustedVolumesVault to=0xC3EBDdEa4f69df717a8f5c89e7cF20C1c0389100 token=WETH amount=1291.16",
        "2026-05-07T06:17:04Z event RFQFill order=0x71b3 signer=0xC3EBDdEa4f69df717a8f5c89e7cF20C1c0389100 nonce=8842 nonceState=unused from=TrustedVolumesVault to=0xC3EBDdEa4f69df717a8f5c89e7cF20C1c0389100 token=USDC amount=1268771",
        "2026-05-07T06:17:06Z event RFQFill order=0x71b3 signer=0xC3EBDdEa4f69df717a8f5c89e7cF20C1c0389100 nonce=8842 nonceState=unused from=TrustedVolumesVault to=0xC3EBDdEa4f69df717a8f5c89e7cF20C1c0389100 token=USDT amount=206282",
        "2026-05-07T06:17:08Z event RFQFill order=0x71b3 signer=0xC3EBDdEa4f69df717a8f5c89e7cF20C1c0389100 nonce=8842 nonceState=unused from=TrustedVolumesVault to=0xC3EBDdEa4f69df717a8f5c89e7cF20C1c0389100 token=WBTC amount=16.93",
        "2026-05-07T06:19:31Z alert outflow_severity=critical resolver=0x9bA0CF1588E1DFA905eC948F7FE5104dD40EDa31 estimate_usd=5870000",
        "2026-05-07T06:22:18Z note aggregator_status 1inch_protocols=not_impacted trustedvolumes_custom_proxy=impacted",
      ].join("\n"),
    },
    "/srv/rfq-desk/tx/primary-transfer.trace": {
      content: [
        "trace_id=mainnet:0x71b3",
        "block=25039670",
        "attacker=0xC3EBDdEa4f69df717a8f5c89e7cF20C1c0389100",
        "victim_resolver=0x9bA0CF1588E1DFA905eC948F7FE5104dD40EDa31",
        "custom_proxy=0xeEeEEe53033F7227d488ae83a",
        "",
        "call sequence:",
        "  01 registerSigner(attacker)",
        "     access check: missing onlyOwner",
        "     result: attacker accepted as trusted signer",
        "",
        "  02 fillRFQ(order=0x71b3, nonce=8842, from=TrustedVolumesVault)",
        "     signature signer: attacker",
        "     replay check: nonce observed but not consumed",
        "     transfer source: calldata.from, not recovered maker",
        "     result: transferFrom(TrustedVolumesVault, attacker, WETH)",
        "",
        "  03 fillRFQ(order=0x71b3, nonce=8842, from=TrustedVolumesVault)",
        "     replay check: same nonce still unused",
        "     result: transferFrom(TrustedVolumesVault, attacker, USDC)",
        "",
        "impact summary:",
        "  - repeated fills reused the same authorization context",
        "  - custom proxy trusted caller-supplied source fields",
        "  - stolen assets were consolidated and swapped toward ETH",
      ].join("\n"),
    },
    "/srv/rfq-desk/containment/checklist.md": {
      content: [
        "first-hour containment",
        "",
        "[x] pause TrustedVolumes custom RFQ proxy",
        "[x] revoke resolver allowances from hot vaults",
        "[x] publish affected-surface statement: custom proxy only",
        "[ ] rotate signer set after patched contract is audited",
        "[ ] redeploy RFQ proxy with owner-gated signer registration",
        "[ ] consume nonce before external token transfer",
        "[ ] derive maker/from from signed order, never calldata",
        "[ ] add invariant tests for replay, signer auth, and payer binding",
        "",
        "customer communication draft:",
        "  1inch standard aggregation routes and user funds are not affected.",
        "  TrustedVolumes' custom resolver path is disabled pending redeploy.",
      ].join("\n"),
    },
  },
  steps: [
    {
      id: "advisory",
      goal: "Read the incident advisory.",
      hint: "`cat ADVISORY.md`.",
      matches: [{ kind: "exact", command: "cat ADVISORY.md" }],
      narration:
        "The blast radius is a custom RFQ proxy and resolver. Start with the three failed controls: signer auth, replay protection, and transfer source validation.",
    },
    {
      id: "config",
      goal: "Open the deployed resolver configuration.",
      hint: "`cat contracts/resolver.config`.",
      matches: [{ kind: "exact", command: "cat contracts/resolver.config" }],
      narration:
        "The config says the intended signer path was owner-gated, but the deployed registerSigner function was public. That turns the attacker into a trusted signer before any order fills.",
    },
    {
      id: "signer-event",
      goal: "Find the signer registration event.",
      hint: "`grep -nF RegisterSigner logs/events.log`.",
      matches: [
        {
          kind: "exact",
          command: "grep -nF RegisterSigner logs/events.log",
        },
      ],
      narration:
        "The caller and signer are the same attacker address, and the status is accepted. That should be impossible for a public caller in an RFQ system.",
    },
    {
      id: "nonce-reuse",
      goal: "Check whether the RFQ nonce was consumed.",
      hint: "`grep -nF nonce=8842 logs/events.log`.",
      matches: [
        { kind: "exact", command: "grep -nF nonce=8842 logs/events.log" },
      ],
      narration:
        "Four fills reuse nonce 8842, and every row still says nonceState=unused. Broken replay protection let one authorization context drain multiple assets.",
    },
    {
      id: "trace",
      goal: "Read the primary transaction trace.",
      hint: "`cat tx/primary-transfer.trace`.",
      matches: [{ kind: "exact", command: "cat tx/primary-transfer.trace" }],
      narration:
        "The decisive bug is not just a bad signer list. The proxy also accepted `from=TrustedVolumesVault` from calldata, then used transferFrom against that source. Source fields must be bound to the signed order, not caller input.",
    },
    {
      id: "containment",
      goal: "Open the containment checklist.",
      hint: "`cat containment/checklist.md`.",
      matches: [
        { kind: "exact", command: "cat containment/checklist.md" },
      ],
      narration:
        "The immediate actions are pause, revoke, and communicate scope. The durable fix is owner-gated signers, consume nonce before external calls, and bind the payer to the signed order.",
    },
  ],
  debrief: {
    summary:
      "On May 7 2026, TrustedVolumes, a DeFi liquidity provider and resolver used by multiple protocols, confirmed an exploit that drained roughly $6.7M. Public reports from Decrypt and crypto.news tied the incident to a TrustedVolumes-controlled custom RFQ swap proxy on Ethereum. Blockchain reporting described about $5.87M initially drained from the resolver, including WETH, USDT, WBTC, and USDC. 1inch stated that its core protocols, infrastructure, systems, and user funds were not impacted.",
    lesson:
      "RFQ systems concentrate trust in small pieces of settlement code. Three invariants should be non-negotiable: only an authorized owner path can add signers, each signed order nonce is consumed before any external transfer, and the token source is recovered from the signed order rather than accepted from calldata. If any one of those is loose, a custom proxy can become a vault drain. If all three are loose at once, the attacker can register, replay, and choose the payer in one chain of calls. Response should separate public aggregator routes from custom resolver paths, pause only the affected surface, revoke allowances from hot vaults, and redeploy only after invariant tests cover signer authorization, replay, and payer binding.",
    simulated: [
      "The host, logs, config file, trace formatting, checklist, and exact event times are invented for the exhibit.",
      "The contract excerpts are simplified and do not include executable exploit code.",
      "The date, approximate loss, affected custom RFQ proxy framing, asset classes, resolver address reported publicly, and 1inch non-impact statement are based on public reports from Decrypt, crypto.news, and other incident coverage.",
    ],
  },
};
